name: Multi Job
on:
    push:
        branches: ["main"]
        paths:
            [
                "github-actions/basics-pipeline/**",
                ".github/workflows/4.multi-jobs.yml",
            ]
jobs:
    build-job:
        name: ðŸ“Œ 1.Build Job
        runs-on: ubuntu-latest
        steps:
            - name: build code
              run: echo "Build Code"
    test-job:
        name: ðŸ“Œ 2.Test Job
        runs-on: ubuntu-latest
        steps:
            - name: test code
              run: echo "Test Code"
    deploy-job:
        name: ðŸ“Œ 3.Deploy Job
        runs-on: ubuntu-latest
        steps:
            - name: deploy code
              run: echo "Deploy Code"
