name: Sequence Multi Job
on:
  push:
    branches: ["main"]
    paths:
      [
        "github-actions/basics-pipeline/**",
        ".github/workflows/5.sequence-multi-jobs.yml",
      ]
jobs:
  build-job:
    name: ðŸ“Œ 1.Build Job
    runs-on: ubuntu-latest
    steps:
      - name: install Cowsay CMD
        run: sudo apt-get install -y cowsay
      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, Iam a DRAGON...RAWR" >> dragon.txt
      - name: Sleep for 30 seconds
        run: sleep 30
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dragon-artifact
          path: dragon.txt
  test-job:
    name: ðŸ“Œ 2.Test Job
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: dragon-artifact
      - name: Sleep for 10 seconds
        run: sleep 10
      - name: Test File Exists
        run: grep -i "dragon" dragon.txt
  deploy-job:
    name: ðŸ“Œ 3.Deploy Job
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: dragon-artifact
      - name: Read File
        run: cat dragon.txt
      - name: Deploy
        run: echo "Deploy Code....."
