name: My First Workflow
on:
  push:
    branches: ["main"]
    paths: ["github-actions/basics-pipeline/**"]
  workflow_dispatch:
jobs:
  first-job:
    name: ðŸ“Œ First Job
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2
      - name: Hello World
        run: echo "Hello World"
      - name: Goodbye World
        run: echo "Goodbye World"
